name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Authenticate GH CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Download submodules
      run: git submodule update --init

    - name: Download Premake
      run: |
        curl -L -o premake5.zip https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip
        unzip premake5.zip -d premake
        echo "$(pwd)/premake" >> $GITHUB_PATH

    - name: Run Premake for solution files
      run: premake/premake5.exe vs2022

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build
      run: dotnet build ${{env.SOLUTION_FILE_PATH}} --configuration ${{env.BUILD_CONFIGURATION}} --no-restore

    - name: Update Latest
      run: |
        gh release delete --cleanup-tag --yes "latest" || true
        sleep 15
        gh release create "latest" --target "main" --title "Latest Auto-Build" Strype-ScriptCore/bin/net8.0/*.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
