name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: Strype-ScriptCore.sln  # or your actual solution file path
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Authenticate GH CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Download submodules
      run: git submodule update --init

    - name: Download Premake
      run: |
        curl -L -o premake5.zip https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip
        unzip premake5.zip -d premake
        echo "$(pwd)/premake" >> $GITHUB_PATH

    - name: Run Premake for solution files
      run: premake/premake5.exe vs2022

    - name: Build with MSBuild
      shell: pwsh
      run: |
        $paths = @(
          "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe",
          "C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe",
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
        )
        $msbuildPath = $null
        foreach ($p in $paths) {
          if (Test-Path $p) {
            $msbuildPath = $p
            break
          }
        }
        if (-not $msbuildPath) {
          Write-Error "MSBuild.exe not found on known paths."
          exit 1
        }
        Write-Host "Using MSBuild at $msbuildPath"
        & $msbuildPath $env:SOLUTION_FILE_PATH /-property:Configuration=$env:BUILD_CONFIGURATION -t:restore,build

    - name: Update Latest
      run: |
        gh release delete --cleanup-tag --yes "latest" || true
        sleep 15
        gh release create "latest" --target "main" --title "Latest Auto-Build" C:\a\Strype-ScriptCore\Strype-ScriptCore\bin\net8.0\Coral.Managed.dll C:\a\Strype-ScriptCore\Strype-ScriptCore\bin\net8.0\Strype-ScriptCore.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
