name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: Strype-ScriptCore.sln  # or your actual solution file path
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Authenticate GH CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Download submodules
      run: git submodule update --init

    - name: Download Premake
      run: |
        curl -L -o premake5.zip https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip
        unzip premake5.zip -d premake
        echo "$(pwd)/premake" >> $GITHUB_PATH

    - name: Run Premake for solution files
      run: premake/premake5.exe vs2022

    - name: Restore NuGet packages
      run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Find MSBuild path
      id: find-msbuild
      run: |
        echo "Looking for MSBuild..."
        msbuildPath=$(vswhere -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe)
        echo "MSBuild found at: $msbuildPath"
        echo "msbuild_path=$msbuildPath" >> $GITHUB_OUTPUT

    - name: Build with MSBuild
      run: |
        "${{ steps.find-msbuild.outputs.msbuild_path }}" ${{ env.SOLUTION_FILE_PATH }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /m
  
    - name: List build outputs
      run: dir Strype-ScriptCore\Strype-ScriptCore\bin\${{ env.BUILD_CONFIGURATION }}\net8.0\

    - name: Update Latest
      run: |
        gh release delete --cleanup-tag --yes "latest" || true
        sleep 15
        gh release create "latest" --target "main" --title "Latest Auto-Build" Strype-ScriptCore\Strype-ScriptCore\bin\${{ env.BUILD_CONFIGURATION }}\net8.0\Coral.Managed.dll Strype-ScriptCore\Strype-ScriptCore\bin\${{ env.BUILD_CONFIGURATION }}\net8.0\Strype-ScriptCore.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
